### ISSUE TITLE
Compilation error after upgrading to v0.20.0-RC1

### ISSUE THREAD

**Issue by marko-asplund** [ovotech/fs2-kafka#205]
I get the following error after upgrading from 0.20.0-M2 to 0.20.0-RC1:
```
[error] /foo/server/src/main/scala/com/abc/def/Server.scala:73:38: Symbol 'type cats.Parallel.Aux' is missing from the classpath.
[error] This symbol is required by 'method cats.effect.IOInstances.ioParallel'.
[error] Make sure that type Aux is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'IOInstances.class' was compiled against an incompatible version of cats.Parallel.
[error]       serverBuilder <- ServerBuilder[IO](httpPort)
[error]                                      ^
[warn] two warnings found
[error] one error found
[error] (server / Compile / compileIncremental) Compilation failed
```

**Comment by vlovgr** [comment]
This is not an issue specific to fs2-kafka, but because of source incompatibility between cats 2.0.0-RC2 and previous versions. Since cats 2.0.0 and cats-effect 2.0.0 is out, we're waiting for fs2 to follow before fs2-kafka will be published for 2.0.0.
